### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-web-widget#32]
When following best-practises for tsconfig.json (here: https://www.totaltypescript.com/tsconfig-cheat-sheet), there is an import issue.

Import code:

```typescript
import * as ftrackWidget from '@ftrack/web-widget';
```

Error:

> Could not find a declaration file for module '@ftrack/web-widget'. '/workspaces/WATS/node_modules/.pnpm/@ftrack+web-widget@1.6.2/node_modules/@ftrack/web-widget/dist/ftrackWidget.es.js' implicitly has an 'any' type.
>   There are types at '/workspaces/WATS/node_modules/@ftrack/web-widget/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@ftrack/web-widget' library may need to update its package.json or typings.

**Comment by ffMathy** [comment]
Here is my full tsconfig:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "strict": true,
    "sourceMap": true,
    "declaration": false,
    "allowSyntheticDefaultImports": true,
    "noUncheckedIndexedAccess": true,
    "moduleResolution": "Bundler",
    "esModuleInterop": true,
    "importHelpers": true,
    "target": "es2022",
    "module": "ESNext",
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "auto",
    "isolatedModules": true,
    "noEmit": true,
    "noEmitHelpers": false,
    "lib": [
      "ES2022",
      "DOM", 
      "DOM.Iterable"
    ],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "types": [
      "reflect-metadata",
      "jest",
      "node"
    ],
    "paths": {
    }
  },
  "exclude": [
    "**/node_modules",
    "tmp"
  ],
  "ts-node": {
    "require": [
      "tsconfig-paths/register"
    ]
  }
}

```

**Comment by ffMathy** [comment]
The offending setting is `isolatedModules: true`.

But that should be possible strictness-wise. The Ftrack JavaScript API does not have this issue.

**Comment by ffMathy** [comment]
It seems the offending setting is `moduleResolution: "Bundler"`.

But that is recommended in our scenario.

**Comment by gismya** [comment]
Thanks for the report. I'll look into it!

**Comment by ffMathy** [comment]
That was quick! Thanks! 😍
